package org.ai.testing.report.generator;

import org.ai.testing.report.dto.TestReportDto;
import org.ai.testing.testcase.dto.TestCaseResultDto;
import org.ai.testing.testrun.dto.TestRunResultDto;
import org.ai.testing.testsuite.dto.TestSuiteExecutionResultDto;
import org.ai.testing.util.Strings;
import org.ai.testing.validation.dto.ValidationResultDto;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

/**
 * A compact summary suited to pull request comments and CI job summaries.
 *
 * <p>New in this version. It leads with failures rather than burying them, so
 * the first screen of a job summary answers "what broke".</p>
 */
public class MarkdownReportGenerator extends AbstractFileReportGenerator {

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public MarkdownReportGenerator() {
        this(Paths.get("reports", "test-report.md"));
    }

    public MarkdownReportGenerator(Path outputPath) {
        super(outputPath, "MARKDOWN");
    }

    @Override
    protected String render(TestReportDto report) {
        TestRunResultDto run = report.getTestRunResult();
        StringBuilder md = new StringBuilder();

        md.append("# ").append(Strings.defaultIfBlank(report.getReportName(), "API Test Report"))
                .append("\n\n");

        md.append(badge(run)).append(' ')
                .append("**").append(run.getPassedTestCases()).append('/')
                .append(run.getTotalTestCases()).append("** test cases passed in ")
                .append(Strings.humanDuration(run.getExecutionTimeMs()))
                .append(".\n\n");

        md.append("| | |\n|---|---|\n");
        md.append("| Run | ").append(escape(run.getRunName())).append(" |\n");
        md.append("| Run ID | `").append(Strings.nullToEmpty(run.getRunId())).append("` |\n");
        md.append("| Environment | ").append(escape(run.getEnvironment())).append(" |\n");
        md.append("| Execution mode | ").append(escape(run.getExecutionMode())).append(" |\n");
        md.append("| Generated | ")
                .append(report.getGeneratedAt() == null
                        ? "" : TIMESTAMP.format(report.getGeneratedAt()))
                .append(" |\n");
        md.append("| Pass rate | ")
                .append(String.format(Locale.ROOT, "%.1f%%", run.getMetrics().getPassRate()))
                .append(" |\n");
        md.append("| Median / p95 latency | ")
                .append(run.getMetrics().getMedianResponseTimeMs()).append(" ms / ")
                .append(run.getMetrics().getP95ResponseTimeMs()).append(" ms |\n\n");

        appendFailures(md, run);
        appendSuites(md, run);
        appendSlowest(md, run);
        appendWarnings(md, run);

        md.append("\n---\n\nGenerated by ")
                .append(Strings.defaultIfBlank(report.getGeneratedBy(), "AI API Testing Agent"));
        if (Strings.hasText(report.getToolVersion())) {
            md.append(' ').append(report.getToolVersion());
        }
        md.append('\n');
        return md.toString();
    }

    private void appendFailures(StringBuilder md, TestRunResultDto run) {
        List<TestCaseResultDto> failures = run.failures();
        if (failures.isEmpty()) {
            md.append("## Failures\n\nNone.\n\n");
            return;
        }

        md.append("## Failures (").append(failures.size()).append(")\n\n");
        for (TestCaseResultDto failure : failures) {
            md.append("### ").append(icon(failure)).append(' ')
                    .append(escape(failure.getTestCaseName()))
                    .append(" — `").append(failure.getMethod()).append(' ')
                    .append(failure.getRequest() == null
                            ? "" : escape(failure.getRequest().getUrl()))
                    .append("`\n\n");
            md.append(escape(failure.getMessage())).append("\n\n");

            List<ValidationResultDto> broken = failure.getValidationSummary().getResults()
                    .stream().filter(result -> !result.isPassed()).toList();
            if (!broken.isEmpty()) {
                md.append("| Assertion | Expected | Actual |\n|---|---|---|\n");
                for (ValidationResultDto validation : broken) {
                    md.append("| ").append(escape(validation.getValidationType()))
                            .append(' ').append(code(validation.getField()))
                            .append(' ').append(escape(Strings.lower(
                                    Strings.nullToEmpty(validation.getOperator()).replace('_', ' '))))
                            .append(" | ").append(code(validation.getExpected()))
                            .append(" | ").append(code(validation.getActual()))
                            .append(" |\n");
                }
                md.append('\n');
            }
            if (Strings.hasText(failure.getErrorDetail())) {
                md.append("```\n").append(failure.getErrorDetail()).append("\n```\n\n");
            }
        }
    }

    private void appendSuites(StringBuilder md, TestRunResultDto run) {
        md.append("## Suites\n\n");
        md.append("| Suite | Status | Passed | Failed | Errored | Skipped | Duration |\n");
        md.append("|---|---|---:|---:|---:|---:|---:|\n");
        for (TestSuiteExecutionResultDto suite : run.getSuiteResults()) {
            md.append("| ").append(escape(suite.getSuiteName()))
                    .append(" | ").append(statusIcon(suite.getStatus().name()))
                    .append(' ').append(suite.getStatus().name())
                    .append(" | ").append(suite.getPassedTestCases())
                    .append(" | ").append(suite.getFailedTestCases())
                    .append(" | ").append(suite.getErroredTestCases())
                    .append(" | ").append(suite.getSkippedTestCases())
                    .append(" | ").append(Strings.humanDuration(suite.getExecutionTimeMs()))
                    .append(" |\n");
        }
        md.append('\n');
    }

    private void appendSlowest(StringBuilder md, TestRunResultDto run) {
        List<TestCaseResultDto> slowest = run.slowestTests(5);
        if (slowest.isEmpty()) {
            return;
        }
        md.append("## Slowest test cases\n\n");
        md.append("| Test case | Method | Status | Latency |\n|---|---|---|---:|\n");
        for (TestCaseResultDto result : slowest) {
            md.append("| ").append(escape(result.getTestCaseName()))
                    .append(" | ").append(Strings.nullToEmpty(result.getMethod()))
                    .append(" | ").append(result.statusCode())
                    .append(" | ").append(result.responseTimeMs()).append(" ms |\n");
        }
        md.append('\n');
    }

    private void appendWarnings(StringBuilder md, TestRunResultDto run) {
        if (run.getWarnings().isEmpty()) {
            return;
        }
        md.append("## Warnings\n\n");
        run.getWarnings().forEach(warning ->
                md.append("- ").append(escape(warning)).append('\n'));
        md.append('\n');
    }

    private String badge(TestRunResultDto run) {
        return switch (run.getStatus()) {
            case PASSED -> "**PASSED**";
            case FAILED -> "**FAILED**";
            case ERROR -> "**ERROR**";
            case SKIPPED -> "**SKIPPED**";
        };
    }

    private String icon(TestCaseResultDto result) {
        return statusIcon(result.getStatus().name());
    }

    private String statusIcon(String status) {
        return switch (status) {
            case "PASSED" -> "\u2705";
            case "FAILED" -> "\u274C";
            case "ERROR" -> "\u26A0\uFE0F";
            default -> "\u23ED\uFE0F";
        };
    }

    private String code(String value) {
        String text = Strings.truncate(Strings.nullToEmpty(value).replace("\n", " "), 80);
        return text.isEmpty() ? "" : "`" + text.replace("`", "'") + "`";
    }

    private String escape(String value) {
        return Strings.nullToEmpty(value).replace("|", "\\|").replace("\n", " ");
    }
}
